### ISSUE TITLE
[ROADMAP] v1.0.0

### ISSUE THREAD

**Issue by vogloblinsky** [compodoc/compodoc#46]
- [x] handle external markdown files as "functional" documentation.
A starting work is located on feature branch "ext-md"

- [x] watch/recompile feature while serving documentation. 
A starting work is located on feature branch "watch-flag".
The issue located here : https://github.com/compodoc/compodoc/issues/20

- [x] rewrite routes page.
A starting work is located on feature branch "router-tree-diagram".
The issue located here : https://github.com/compodoc/compodoc/issues/17

- [x] others TODOS in related project : https://github.com/compodoc/compodoc/projects/2
